#!/bin/bash
#
# logsd        Startup script for log server.
#
# chkconfig: 2345 12 88
### BEGIN INIT INFO
# Provides: $syslog
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start or Stop the log server.
### END INIT INFO

# Source function library.

RETVAL=0
rdir=`pwd`
PIDFILE=$rdir/ts.pid
lockfile=$rdir/ts.lock
exec=$rdir/TServer
start() {
	[ -x $exec ] || exit 5

	umask 077

        echo -n $"Starting log server: "
        daemonize -c $rdir -p $PIDFILE -l $lockfile $exec
        RETVAL=$?
	echo
        [ $RETVAL -eq 0 ] && touch $lockfile
	return $RETVAL
}
stop() {
        echo -n $"Shutting down log server: "
	sname=`uname`
        if [ "Darwin" = $sname ];then
	  kill `cat $PIDFILE`
	else
	  killproc -p "$PIDFILE" $exec
        fi
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
esac

exit $?
